(function(){
'use strict';
var app=document.getElementById('app');
var p=new URLSearchParams(location.search);
var path=location.pathname;
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
function hero(){return '<section class="hero"><h1>מטנקי עמק הבכא לטנקיסטיות בחולית</h1><p>מסיפורי הגבורה של מלחמת יום הכיפורים אל גבורת שבעה באוקטובר</p><div class="question">מה גורם לאדם לקבל אחריות ולפעול כאשר הכול סביבו משתבש?</div></section>';}
function teacherUrl(code,token){return location.origin+'/teacher?code='+encodeURIComponent(code)+'&token='+encodeURIComponent(token);}
async function access(body){var r=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});var d={};try{d=await r.json();}catch(e){}if(!r.ok){var er=new Error(d.error||'request');er.code=d.error;throw er;}return d;}
function storeTeacher(code,token){var u=teacherUrl(code,token);try{localStorage.setItem('tanks-hulit-teacher-'+code,token);localStorage.setItem('tanks-hulit-last-code',code);localStorage.setItem('tanks-hulit-last-room',u);}catch(e){}return u;}
function msg(code){var map={bad_pin:'קוד המורה צריך להכיל 4–6 ספרות.',bad_code:'קוד הכיתה צריך להכיל 6 ספרות.',room_not_found:'לא נמצאה כיתה עם הקוד הזה.',invalid_credentials:'קוד הכיתה או קוד המורה אינם נכונים.',pin_not_set:'הכיתה הזו נוצרה לפני מנגנון השמירה. פתחו אותה מהקישור המקורי והגדירו קוד מורה.',too_many_attempts:'בוצעו יותר מדי ניסיונות. המתינו כמה דקות ונסו שוב.'};return map[code]||'לא הצלחנו להשלים את הפעולה. נסו שוב.';}
function renderAccessHome(){
 var recent='';try{recent=localStorage.getItem('tanks-hulit-last-room')||'';}catch(e){}
 app.innerHTML=hero()+'<div class="access-intro"><div><strong>ניהול כיתה נשמר אוטומטית</strong><span>אותו קוד כיתה יכול ללוות אתכם גם במפגש הבא.</span></div><div class="access-saved-badge">שמירה עד 30 יום מהפעילות האחרונה</div></div><div class="grid two access-grid"><section class="card access-card"><div class="access-icon">＋</div><h2>כיתה חדשה</h2><p class="muted">צרו חדר חדש ובחרו קוד מורה אישי. התלמידים יקבלו רק את קוד הכיתה או ה־QR.</p><div class="field"><label for="accessClassName">שם הכיתה — לא חובה</label><input id="accessClassName" maxlength="60" placeholder="לדוגמה: י׳2"></div><div class="field"><label for="accessNewPin">קוד מורה אישי</label><input id="accessNewPin" class="access-pin" type="password" inputmode="numeric" autocomplete="new-password" maxlength="6" placeholder="4–6 ספרות"><div class="tiny">הקוד נדרש רק למורה, כדי לחזור לכיתה ממחשב אחר.</div></div><div id="newRoomError" class="access-error"></div><button class="btn pri access-main-btn" id="accessCreate">יצירת כיתה חדשה</button></section><section class="card access-card"><div class="access-icon">↩</div><h2>המשך כיתה קיימת</h2><p class="muted">חזרו לסקר, לענן הערכים ולשלב שבו עצרתם.</p><div class="field"><label for="accessRoomCode">קוד כיתה</label><input id="accessRoomCode" class="access-code" inputmode="numeric" maxlength="6" placeholder="6 ספרות"></div><div class="field"><label for="accessResumePin">קוד מורה</label><input id="accessResumePin" class="access-pin" type="password" inputmode="numeric" autocomplete="current-password" maxlength="6" placeholder="4–6 ספרות"></div><div id="resumeRoomError" class="access-error"></div><button class="btn teal access-main-btn" id="accessResume">המשך כיתה קיימת</button>'+(recent?'<div class="access-divider"><span>או</span></div><button class="btn ghost access-main-btn" id="accessRecent">פתיחת הכיתה האחרונה במכשיר זה</button>':'')+'</section></div><section class="card access-note"><strong>מה נשמר?</strong><span>הצבעות בסקר, ענן הערכים, חשיפת התוצאות והשלב הפעיל — הכול נשאר באותו חדר.</span></section>';
 document.getElementById('accessCreate').onclick=async function(){var b=this,err=document.getElementById('newRoomError');err.textContent='';var pin=(document.getElementById('accessNewPin').value||'').trim();var className=(document.getElementById('accessClassName').value||'').trim();if(!/^\d{4,6}$/.test(pin)){err.textContent=msg('bad_pin');return;}b.disabled=true;b.textContent='יוצר כיתה…';try{var d=await access({action:'create',className:className,pin:pin});location.href=storeTeacher(d.code,d.teacherToken);}catch(e){err.textContent=msg(e.code);b.disabled=false;b.textContent='יצירת כיתה חדשה';}};
 document.getElementById('accessResume').onclick=async function(){var b=this,err=document.getElementById('resumeRoomError');err.textContent='';var code=(document.getElementById('accessRoomCode').value||'').replace(/\D/g,'').slice(0,6);var pin=(document.getElementById('accessResumePin').value||'').trim();if(code.length!==6){err.textContent=msg('bad_code');return;}if(!/^\d{4,6}$/.test(pin)){err.textContent=msg('bad_pin');return;}b.disabled=true;b.textContent='פותח כיתה…';try{var d=await access({action:'resume',code:code,pin:pin});location.href=storeTeacher(d.code,d.teacherToken);}catch(e){err.textContent=msg(e.code);b.disabled=false;b.textContent='המשך כיתה קיימת';}};
 if(recent)document.getElementById('accessRecent').onclick=function(){location.href=recent;};
}
function pinDialog(code,token){var old=document.getElementById('teacherPinOverlay');if(old)old.remove();var o=document.createElement('div');o.id='teacherPinOverlay';o.className='access-overlay';o.innerHTML='<div class="access-dialog"><button class="access-dialog-close" id="pinDialogClose">×</button><div class="eyebrow">גישה למורה</div><h2>הגדרת קוד מורה</h2><p class="muted">בחרו 4–6 ספרות שתוכלו לזכור. הקוד לא יוצג לתלמידים.</p><div class="field"><input id="teacherPinInput" type="password" inputmode="numeric" maxlength="6" placeholder="4–6 ספרות"></div><div id="teacherPinError" class="access-error"></div><button class="btn pri" id="teacherPinSave">שמירת קוד המורה</button></div>';document.body.appendChild(o);var close=function(){o.remove();};document.getElementById('pinDialogClose').onclick=close;o.onclick=function(e){if(e.target===o)close();};document.getElementById('teacherPinSave').onclick=async function(){var b=this,pin=(document.getElementById('teacherPinInput').value||'').trim(),err=document.getElementById('teacherPinError');err.textContent='';if(!/^\d{4,6}$/.test(pin)){err.textContent=msg('bad_pin');return;}b.disabled=true;b.textContent='שומר…';try{await access({action:'setPin',code:code,teacherToken:token,pin:pin});b.textContent='נשמר ✓';setTimeout(close,650);}catch(e){err.textContent=msg(e.code);b.disabled=false;b.textContent='שמירת קוד המורה';}};}
function injectTeacherAccess(){if(path!=='/teacher')return;var code=p.get('code')||'',token='';try{token=p.get('token')||localStorage.getItem('tanks-hulit-teacher-'+code)||'';}catch(e){token=p.get('token')||'';}if(!code||!token)return;try{storeTeacher(code,token);}catch(e){}var first=document.querySelector('main#app > section.card:first-child');if(!first||document.getElementById('teacherAccessBar'))return;var bar=document.createElement('div');bar.id='teacherAccessBar';bar.className='teacher-access-bar';bar.innerHTML='<div class="teacher-access-state"><span class="teacher-access-dot">✓</span><div><strong>הכיתה נשמרת אוטומטית</strong><small>אפשר לחזור אליה עם קוד הכיתה וקוד המורה.</small></div></div><div class="teacher-access-actions"><button class="btn ghost" id="copyTeacherLink">העתקת קישור מורה</button><button class="btn ghost" id="changeTeacherPin">הגדרת / שינוי קוד מורה</button></div>';var strip=first.querySelector('.stage-strip');if(strip)strip.before(bar);else first.appendChild(bar);document.getElementById('copyTeacherLink').onclick=async function(){try{await navigator.clipboard.writeText(teacherUrl(code,token));var b=this,t=b.textContent;b.textContent='הקישור הועתק ✓';setTimeout(function(){if(b)b.textContent=t;},1200);}catch(e){}};document.getElementById('changeTeacherPin').onclick=function(){pinDialog(code,token);};}
if(path==='/'||path===''){renderAccessHome();}else if(path==='/teacher'){injectTeacherAccess();new MutationObserver(injectTeacherAccess).observe(app,{childList:true,subtree:true});setTimeout(function(){var code=p.get('code')||'',token='';try{token=p.get('token')||localStorage.getItem('tanks-hulit-teacher-'+code)||'';}catch(e){token=p.get('token')||'';}if(code&&token)access({action:'touch',code:code,teacherToken:token}).catch(function(){});},700);}
})();
